/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DocsInstallRouteImport } from './routes/docs.install'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCompilationsNewRouteImport } from './routes/app.compilations.new'
import { Route as AppCompilationsIdRouteImport } from './routes/app.compilations.$id'
import { Route as AppCompilationsIdTestsRouteImport } from './routes/app.compilations.$id.tests'
import { Route as AppCompilationsIdReceiptRouteImport } from './routes/app.compilations.$id.receipt'
import { Route as AppCompilationsIdCompareRouteImport } from './routes/app.compilations.$id.compare'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/docs/install',
  path: '/docs/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCompilationsNewRoute = AppCompilationsNewRouteImport.update({
  id: '/compilations/new',
  path: '/compilations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCompilationsIdRoute = AppCompilationsIdRouteImport.update({
  id: '/compilations/$id',
  path: '/compilations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCompilationsIdTestsRoute = AppCompilationsIdTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppCompilationsIdRoute,
} as any)
const AppCompilationsIdReceiptRoute =
  AppCompilationsIdReceiptRouteImport.update({
    id: '/receipt',
    path: '/receipt',
    getParentRoute: () => AppCompilationsIdRoute,
  } as any)
const AppCompilationsIdCompareRoute =
  AppCompilationsIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AppCompilationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/app/history': typeof AppHistoryRoute
  '/docs/install': typeof DocsInstallRoute
  '/app/': typeof AppIndexRoute
  '/app/compilations/$id': typeof AppCompilationsIdRouteWithChildren
  '/app/compilations/new': typeof AppCompilationsNewRoute
  '/app/compilations/$id/compare': typeof AppCompilationsIdCompareRoute
  '/app/compilations/$id/receipt': typeof AppCompilationsIdReceiptRoute
  '/app/compilations/$id/tests': typeof AppCompilationsIdTestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/app/history': typeof AppHistoryRoute
  '/docs/install': typeof DocsInstallRoute
  '/app': typeof AppIndexRoute
  '/app/compilations/$id': typeof AppCompilationsIdRouteWithChildren
  '/app/compilations/new': typeof AppCompilationsNewRoute
  '/app/compilations/$id/compare': typeof AppCompilationsIdCompareRoute
  '/app/compilations/$id/receipt': typeof AppCompilationsIdReceiptRoute
  '/app/compilations/$id/tests': typeof AppCompilationsIdTestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/app/history': typeof AppHistoryRoute
  '/docs/install': typeof DocsInstallRoute
  '/app/': typeof AppIndexRoute
  '/app/compilations/$id': typeof AppCompilationsIdRouteWithChildren
  '/app/compilations/new': typeof AppCompilationsNewRoute
  '/app/compilations/$id/compare': typeof AppCompilationsIdCompareRoute
  '/app/compilations/$id/receipt': typeof AppCompilationsIdReceiptRoute
  '/app/compilations/$id/tests': typeof AppCompilationsIdTestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/privacy'
    | '/app/history'
    | '/docs/install'
    | '/app/'
    | '/app/compilations/$id'
    | '/app/compilations/new'
    | '/app/compilations/$id/compare'
    | '/app/compilations/$id/receipt'
    | '/app/compilations/$id/tests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/privacy'
    | '/app/history'
    | '/docs/install'
    | '/app'
    | '/app/compilations/$id'
    | '/app/compilations/new'
    | '/app/compilations/$id/compare'
    | '/app/compilations/$id/receipt'
    | '/app/compilations/$id/tests'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/privacy'
    | '/app/history'
    | '/docs/install'
    | '/app/'
    | '/app/compilations/$id'
    | '/app/compilations/new'
    | '/app/compilations/$id/compare'
    | '/app/compilations/$id/receipt'
    | '/app/compilations/$id/tests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  PrivacyRoute: typeof PrivacyRoute
  DocsInstallRoute: typeof DocsInstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/docs/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compilations/new': {
      id: '/app/compilations/new'
      path: '/compilations/new'
      fullPath: '/app/compilations/new'
      preLoaderRoute: typeof AppCompilationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compilations/$id': {
      id: '/app/compilations/$id'
      path: '/compilations/$id'
      fullPath: '/app/compilations/$id'
      preLoaderRoute: typeof AppCompilationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compilations/$id/tests': {
      id: '/app/compilations/$id/tests'
      path: '/tests'
      fullPath: '/app/compilations/$id/tests'
      preLoaderRoute: typeof AppCompilationsIdTestsRouteImport
      parentRoute: typeof AppCompilationsIdRoute
    }
    '/app/compilations/$id/receipt': {
      id: '/app/compilations/$id/receipt'
      path: '/receipt'
      fullPath: '/app/compilations/$id/receipt'
      preLoaderRoute: typeof AppCompilationsIdReceiptRouteImport
      parentRoute: typeof AppCompilationsIdRoute
    }
    '/app/compilations/$id/compare': {
      id: '/app/compilations/$id/compare'
      path: '/compare'
      fullPath: '/app/compilations/$id/compare'
      preLoaderRoute: typeof AppCompilationsIdCompareRouteImport
      parentRoute: typeof AppCompilationsIdRoute
    }
  }
}

interface AppCompilationsIdRouteChildren {
  AppCompilationsIdCompareRoute: typeof AppCompilationsIdCompareRoute
  AppCompilationsIdReceiptRoute: typeof AppCompilationsIdReceiptRoute
  AppCompilationsIdTestsRoute: typeof AppCompilationsIdTestsRoute
}

const AppCompilationsIdRouteChildren: AppCompilationsIdRouteChildren = {
  AppCompilationsIdCompareRoute: AppCompilationsIdCompareRoute,
  AppCompilationsIdReceiptRoute: AppCompilationsIdReceiptRoute,
  AppCompilationsIdTestsRoute: AppCompilationsIdTestsRoute,
}

const AppCompilationsIdRouteWithChildren =
  AppCompilationsIdRoute._addFileChildren(AppCompilationsIdRouteChildren)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCompilationsIdRoute: typeof AppCompilationsIdRouteWithChildren
  AppCompilationsNewRoute: typeof AppCompilationsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppCompilationsIdRoute: AppCompilationsIdRouteWithChildren,
  AppCompilationsNewRoute: AppCompilationsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  PrivacyRoute: PrivacyRoute,
  DocsInstallRoute: DocsInstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
